// teammateapp.au — shared page behaviour (every page loads this, deferred;
// each block below checks for its own elements first).
// The header menus are plain <details>, so they already open and close
// without JS; this only adds the polish: one menu open at a time, close on
// a click outside, on Escape or on following a link, and no page scroll
// behind the full-screen phone menu.
(function () {
  var menus = Array.prototype.slice.call(document.querySelectorAll(".nav details"));
  if (!menus.length) return;

  function sync() {
    var phoneMenu = document.querySelector(".nav-menu");
    document.documentElement.classList.toggle("menu-open", !!(phoneMenu && phoneMenu.open));
  }

  menus.forEach(function (d) {
    d.addEventListener("toggle", function () {
      if (d.open) menus.forEach(function (o) { if (o !== d) o.open = false; });
      sync();
    });
    d.addEventListener("click", function (e) {
      if (e.target.closest("a")) d.open = false;
    });
  });

  document.addEventListener("click", function (e) {
    menus.forEach(function (d) { if (d.open && !d.contains(e.target)) d.open = false; });
  });

  document.addEventListener("keydown", function (e) {
    if (e.key !== "Escape") return;
    menus.forEach(function (d) {
      if (d.open) { d.open = false; d.querySelector("summary").focus(); }
    });
  });

  // Phone menu is display:none above 900px (styles.css); if the window
  // grows while it's open, close it so the scroll lock can't stick.
  window.addEventListener("resize", function () {
    var m = document.querySelector(".nav-menu");
    if (m && m.open && window.innerWidth > 900) m.open = false;
  });

  // The Industries menu's photos are lazy (closed <details>), so the first
  // open showed grey boxes for a moment: start fetching them as soon as the
  // pointer or keyboard reaches "Industries".
  var drop = document.querySelector(".nav-drop");
  if (drop) {
    var warm = function () {
      drop.querySelectorAll("img").forEach(function (img) { new Image().src = img.src; });
      drop.removeEventListener("pointerenter", warm);
      drop.removeEventListener("focusin", warm);
    };
    drop.addEventListener("pointerenter", warm);
    drop.addEventListener("focusin", warm);
  }
})();

// Homepage industry switcher (scripts/marketing-pages.mjs renders it).
// Without this script every panel shows stacked and the tab row stays
// hidden; with it, one industry at a time. Arrow keys, Home and End move
// between tabs (WAI-ARIA tabs pattern). No auto-rotate: the desktop page
// stays still unless the visitor acts (owner direction 2026-09-11). All
// six tabs are always in view (two rows on phones), so the row never
// scrolls sideways (owner 2026-10-06).
(function () {
  var root = document.querySelector("[data-showcase]");
  if (!root) return;
  var list = root.querySelector(".sc-tabs");
  var tabs = Array.prototype.slice.call(root.querySelectorAll(".sc-tab"));
  if (!list || !tabs.length) return;

  function select(tab, focus) {
    tabs.forEach(function (t) {
      var on = t === tab;
      t.setAttribute("aria-selected", on ? "true" : "false");
      t.tabIndex = on ? 0 : -1;
      document.getElementById(t.getAttribute("aria-controls")).hidden = !on;
    });
    if (focus) tab.focus();
  }

  tabs.forEach(function (t, i) {
    t.addEventListener("click", function () { select(t, false); });
    t.addEventListener("keydown", function (e) {
      var n = { ArrowRight: i + 1, ArrowLeft: i - 1, Home: 0, End: tabs.length - 1 }[e.key];
      if (n === undefined) return;
      e.preventDefault();
      select(tabs[(n + tabs.length) % tabs.length], true);
    });
  });

  list.hidden = false;
  root.classList.add("is-tabs");
  select(tabs[0], false);
})();

// Homepage hero A2, "The Signature, in hand" (owner pick 2026-10-07).
// Hover or focus a crew card and "work" in the h1 becomes that crew while
// the phone in the owner's hand-held photo lights with that industry's
// real Home screen; leave and it settles back to the untouched photo. On
// a desktop nothing moves by itself. Touch screens (hover: none — phones,
// tablets and iPad landscape) step through the crews every 2.5s while the
// hero is on screen, pausing whenever the visitor touches the row or tabs
// onto a card, with a Pause / Play button (WCAG 2.2.2); never under
// reduced motion. In the swipeable row (under 1000px) the crew snapped to
// the centre drives the headline. The h1 keeps its real text: crew words
// are aria-hidden overlays and "work" only fades, so screen readers always
// hear one stable line. Per-crew data (word, screen, alt text, clock) is
// on each card's data-* attributes, generated by
// scripts/marketing-pages.mjs. Without this script the hero is the plain
// tagline, six links and the owner's photo.
(function () {
  var hero = document.querySelector(".hero.sig");
  if (!hero) return;
  var slot = hero.querySelector("[data-slot]");
  var row = hero.querySelector(".crews");
  var hand = hero.querySelector("[data-hp]");
  var cards = Array.prototype.slice.call(hero.querySelectorAll(".crew[data-key]"));
  if (!slot || !row || !hand || !cards.length) return;
  var stage = hand.querySelector(".hp-stage");
  var glass = hand.querySelector(".hp-glass");
  if (!stage || !glass) return;

  var mq = function (q) { try { return window.matchMedia(q); } catch (e) { return { matches: false }; } };
  var reduce = mq("(prefers-reduced-motion: reduce)");
  var rowMode = mq("(max-width: 999px)");
  var touchCycle = mq("(hover: none)");
  var byKey = {};
  cards.forEach(function (c) { byKey[c.getAttribute("data-key")] = c; });

  // ---- the phone in the hand ----
  // The glass corners in the 1712 x 2560 render (TL TR BR BL), measured by
  // scripts/composite-hero-hand.mjs; scripts/prep-hero-hand.mjs punches
  // the same quad out of the photo. A 1000 x 2198 box is warped onto it.
  var HAND_QUAD = [[257, 284], [1175, 119], [1553, 2169], [605, 2337]];
  var GW = 1000, GH = 2198, PW = 1712;
  function homography(p) { // unit square -> quad
    var dx1 = p[1][0] - p[2][0], dx2 = p[3][0] - p[2][0], dy1 = p[1][1] - p[2][1], dy2 = p[3][1] - p[2][1];
    var sx = p[0][0] - p[1][0] + p[2][0] - p[3][0], sy = p[0][1] - p[1][1] + p[2][1] - p[3][1];
    var den = dx1 * dy2 - dx2 * dy1;
    var g = (sx * dy2 - sy * dx2) / den, h = (dx1 * sy - dy1 * sx) / den;
    return [p[1][0] - p[0][0] + g * p[1][0], p[3][0] - p[0][0] + h * p[3][0], p[0][0],
            p[1][1] - p[0][1] + g * p[1][1], p[3][1] - p[0][1] + h * p[3][1], p[0][1], g, h];
  }
  function fitGlass() {
    var s = stage.offsetWidth / PW;
    if (!s) return;
    var m = homography(HAND_QUAD.map(function (q) { return [q[0] * s, q[1] * s]; }));
    var a = m[0] / GW, d = m[3] / GW, g = m[6] / GW, b = m[1] / GH, e = m[4] / GH, h = m[7] / GH;
    glass.style.transform = "matrix3d(" + [a, d, 0, g, b, e, 0, h, 0, 0, 1, 0, m[2], m[5], 0, 1].join(",") + ")";
  }
  // status bar either side of the photo's island; its clock follows the
  // screenshot shown (each card's data-time)
  var bar = document.createElement("div");
  bar.className = "hp-status";
  bar.setAttribute("aria-hidden", "true");
  bar.innerHTML = '<span data-hp-time>9:41</span><svg viewBox="0 0 78 14" aria-hidden="true">' +
    '<rect x="0" y="9" width="3.4" height="5" rx="1" fill="currentColor"/><rect x="5" y="6.5" width="3.4" height="7.5" rx="1" fill="currentColor"/>' +
    '<rect x="10" y="4" width="3.4" height="10" rx="1" fill="currentColor"/><rect x="15" y="1.5" width="3.4" height="12.5" rx="1" fill="currentColor"/>' +
    '<path d="M31 3.6a10.6 10.6 0 0 1 7.4 3l1.4-1.4A12.6 12.6 0 0 0 31 1.6a12.6 12.6 0 0 0-8.8 3.6l1.4 1.4a10.6 10.6 0 0 1 7.4-3Zm0 4a6.6 6.6 0 0 1 4.6 1.9l1.4-1.4a8.6 8.6 0 0 0-12 0l1.4 1.4A6.6 6.6 0 0 1 31 7.6Zm0 4a2.6 2.6 0 0 1 1.8.7L31 14l-1.8-1.7a2.6 2.6 0 0 1 1.8-.7Z" fill="currentColor"/>' +
    '<rect x="47.5" y="1.5" width="25" height="11.5" rx="3.6" fill="none" stroke="currentColor" stroke-opacity=".4"/><rect x="50" y="4" width="17" height="6.5" rx="2" fill="currentColor"/>' +
    '<path d="M74.5 5.3v4.4a2.2 2.2 0 0 0 0-4.4Z" fill="currentColor" fill-opacity=".45"/></svg>';
  glass.appendChild(bar);
  var clock = bar.querySelector("[data-hp-time]");
  fitGlass();
  if (window.ResizeObserver) new ResizeObserver(fitGlass).observe(stage);
  else window.addEventListener("resize", fitGlass);

  // screens load on demand (the splash is the photo itself)
  var shots = {}, want = null;
  function shot(key) {
    var card = byKey[key];
    if (!card) return null;
    if (shots[key]) return shots[key];
    var img = document.createElement("img");
    img.className = "hp-screen";
    img.alt = card.getAttribute("data-screen-alt") || "";
    img.width = 600; img.height = 1301; img.decoding = "async";
    img.setAttribute("aria-hidden", "true");
    img.src = card.getAttribute("data-screen");
    glass.appendChild(img);
    shots[key] = img;
    return img;
  }
  function setScreen(key) {
    want = key;
    if (!key) { hand.classList.remove("is-lit"); return; }
    var img = shot(key);
    if (!img) return;
    function show() {
      if (want !== key) return;
      Object.keys(shots).forEach(function (k) {
        var on = k === key;
        shots[k].classList.toggle("is-on", on);
        if (on) shots[k].removeAttribute("aria-hidden"); else shots[k].setAttribute("aria-hidden", "true");
      });
      clock.textContent = byKey[key].getAttribute("data-time") || "9:41";
      hand.classList.add("is-lit");
    }
    if (img.complete && img.naturalWidth) show(); else img.addEventListener("load", show, { once: true });
  }
  function preloadAll() { cards.forEach(function (c) { shot(c.getAttribute("data-key")); }); }

  // ---- the word slot ----
  // The real word stays in the h1 (screen readers and crawlers always get
  // "Your work crew, sorted."). It only fades to transparent while an
  // aria-hidden crew word is laid over it.
  var homeWord = slot.textContent.trim();
  slot.textContent = "";
  var home = document.createElement("span");
  home.className = "slot-w slot-home";
  home.textContent = homeWord;
  slot.appendChild(home);
  slot.classList.add("is-live");
  var cur = home, curWord = homeWord;
  function fit(noAnim) {
    if (noAnim) slot.style.transition = "none";
    slot.style.width = cur.offsetWidth + "px";
    if (noAnim) { slot.getBoundingClientRect(); slot.style.transition = ""; }
  }
  fit(true);

  function setWord(w) {
    if (w === curWord) return;
    curWord = w;
    var old = cur, next;
    if (w === homeWord) {
      next = home;
      next.classList.add("is-enter");
      next.classList.remove("is-leave");
    } else {
      next = document.createElement("span");
      next.className = "slot-w is-enter";
      next.setAttribute("aria-hidden", "true");
      next.textContent = w;
      slot.appendChild(next);
    }
    cur = next;
    old.classList.add("is-leave");
    next.getBoundingClientRect();
    next.classList.remove("is-enter");
    slot.style.width = next.offsetWidth + "px";
    if (old !== home) setTimeout(function () { if (old.parentNode) old.parentNode.removeChild(old); }, 320);
  }

  // ---- one active crew at a time ----
  var active = null;
  function activate(card) {
    if (active === card) return;
    if (active) active.classList.remove("is-active");
    active = card;
    if (card) {
      card.classList.add("is-active");
      setWord(card.getAttribute("data-word"));
      setScreen(card.getAttribute("data-key"));
    } else {
      setWord(homeWord);
      setScreen(null);
    }
  }

  // ---- desktop: hover / focus ----
  var leaveTimer;
  function settle() {
    var f = document.activeElement;
    if (f && cards.indexOf(f) > -1) { activate(f); return; }
    if (rowMode.matches) return; // the row keeps its centred crew
    activate(null);
  }
  cards.forEach(function (c) {
    c.addEventListener("pointerenter", function (e) {
      if (e.pointerType === "touch" || rowMode.matches) return;
      clearTimeout(leaveTimer);
      activate(c);
    });
    c.addEventListener("pointerleave", function (e) {
      if (e.pointerType === "touch" || rowMode.matches) return;
      clearTimeout(leaveTimer);
      leaveTimer = setTimeout(settle, 160);
    });
    c.addEventListener("focus", function () {
      clearTimeout(leaveTimer);
      activate(c);
      if (rowMode.matches) centre(c, true);
    });
    c.addEventListener("blur", function () {
      clearTimeout(leaveTimer);
      leaveTimer = setTimeout(settle, 160);
    });
  });
  // the hand holds the crew you came from, so you can move onto it to
  // read the screen; leaving it settles back like leaving a card
  var handCard = hero.querySelector(".sig-hand");
  if (handCard) {
    handCard.addEventListener("pointerenter", function (e) {
      if (e.pointerType !== "touch" && !rowMode.matches) clearTimeout(leaveTimer);
    });
    handCard.addEventListener("pointerleave", function (e) {
      if (e.pointerType === "touch" || rowMode.matches) return;
      clearTimeout(leaveTimer);
      leaveTimer = setTimeout(settle, 160);
    });
  }
  // fetch the six screens once the page is idle (arc layout only;
  // ~300 KB), so the first hover crossfades without a wait
  function idlePreload() {
    if (rowMode.matches) return;
    var idle = window.requestIdleCallback || function (f) { return setTimeout(f, 1200); };
    idle(preloadAll);
  }
  if (document.readyState === "complete") idlePreload();
  else window.addEventListener("load", idlePreload);
  row.addEventListener("pointerenter", function () { if (!rowMode.matches) preloadAll(); }, { once: true });

  // ---- row mode: the centred crew drives the headline ----
  var programmatic = false, progTimer, spyTicking = false;
  function centre(card, smooth) {
    if (!rowMode.matches) return; // the arc never scrolls
    var r = row.getBoundingClientRect(), cr = card.getBoundingClientRect();
    var delta = (cr.left + cr.width / 2) - (r.left + r.width / 2);
    if (Math.abs(delta) < 2) return;
    programmatic = true;
    clearTimeout(progTimer);
    progTimer = setTimeout(function () { programmatic = false; }, 900);
    try {
      row.scrollTo({ left: row.scrollLeft + delta, behavior: smooth && !reduce.matches ? "smooth" : "auto" });
    } catch (e) { row.scrollLeft += delta; }
  }
  function centredCard() {
    var r = row.getBoundingClientRect(), mid = r.left + r.width / 2, best = null, bestD = Infinity;
    cards.forEach(function (c) {
      var cr = c.getBoundingClientRect(), d = Math.abs(cr.left + cr.width / 2 - mid);
      if (d < bestD) { bestD = d; best = c; }
    });
    return best;
  }
  row.addEventListener("scroll", function () {
    if (!rowMode.matches || programmatic || spyTicking) return;
    spyTicking = true;
    requestAnimationFrame(function () {
      spyTicking = false;
      var c = centredCard();
      if (c && c !== active) { activate(c); step = cards.indexOf(c); }
    });
  }, { passive: true });

  // ---- touch screens only: the gentle cycle, with a pause button ----
  var step = -1, pausedUntil = 0, stopped = false;
  var pauseBtn = hero.querySelector("[data-pause]");
  var pauseLabel = pauseBtn && pauseBtn.querySelector("[data-pause-label]");
  function cycling() { return touchCycle.matches && !reduce.matches; }
  function syncPause() {
    if (!pauseBtn || !pauseLabel) return;
    pauseBtn.hidden = !cycling();
    pauseBtn.classList.toggle("is-paused", stopped);
    pauseLabel.textContent = stopped ? "Play" : "Pause";
    pauseBtn.setAttribute("aria-label", stopped ? "Play: step through the crews" : "Pause: stop stepping through the crews");
  }
  if (pauseBtn) {
    pauseBtn.addEventListener("click", function () {
      stopped = !stopped;
      if (!stopped) pausedUntil = 0;
      syncPause();
    });
  }
  syncPause();
  [reduce, touchCycle].forEach(function (m) {
    try { m.addEventListener("change", syncPause); }
    catch (e) { try { m.addListener(syncPause); } catch (e2) { /* static is fine */ } }
  });
  function pause(ms) { pausedUntil = Date.now() + ms; }
  ["touchstart", "pointerdown", "wheel"].forEach(function (ev) {
    row.addEventListener(ev, function () {
      pause(6000);
      programmatic = false;            // the visitor's own swipe always wins
      clearTimeout(progTimer);
    }, { passive: true });
  });
  row.addEventListener("touchend", function () { pause(4000); }, { passive: true });
  function tick() {
    if (stopped || !cycling() || document.hidden) return;
    if (Date.now() < pausedUntil) return;
    if (cards.indexOf(document.activeElement) > -1) return; // keyboard on a card
    var hr = hero.getBoundingClientRect();
    if (hr.bottom < 120 || hr.top > window.innerHeight) return;
    step = (step + 1) % (cards.length + 1);       // six crews, then "work"
    var c = cards[step] || null;
    activate(c);
    centre(c || cards[1], true);              // row only; "work": back to the opening view
    var next = cards[step + 1];
    if (next) shot(next.getAttribute("data-key")); // fetch one ahead
  }
  setInterval(tick, 2500);

  // row mode opens on the second crew, so there's a neighbour on each
  // side (and it's plain the row scrolls both ways); nothing is
  // "active" until the visitor swipes or the cycle starts
  function openRow() { if (rowMode.matches && cards[1]) centre(cards[1], false); }
  openRow();

  // ---- keep the slot measured; switching layouts clears the state ----
  var wasRow = rowMode.matches, resizeTicking = false;
  window.addEventListener("resize", function () {
    if (resizeTicking) return;
    resizeTicking = true;
    requestAnimationFrame(function () {
      resizeTicking = false;
      fit(true);
      syncPause();
      if (wasRow !== rowMode.matches) { wasRow = rowMode.matches; activate(null); step = -1; openRow(); }
    });
  });
})();
