// teammateapp.au — shared page behaviour (every page loads this, deferred;
// each block below checks for its own elements first).
// The header menus are plain <details>, so they already open and close
// without JS; this only adds the polish: one menu open at a time, close on
// a click outside, on Escape or on following a link, and no page scroll
// behind the full-screen phone menu.
(function () {
  var menus = Array.prototype.slice.call(document.querySelectorAll(".nav details"));
  if (!menus.length) return;

  function sync() {
    var phoneMenu = document.querySelector(".nav-menu");
    document.documentElement.classList.toggle("menu-open", !!(phoneMenu && phoneMenu.open));
  }

  menus.forEach(function (d) {
    d.addEventListener("toggle", function () {
      if (d.open) menus.forEach(function (o) { if (o !== d) o.open = false; });
      sync();
    });
    d.addEventListener("click", function (e) {
      if (e.target.closest("a")) d.open = false;
    });
  });

  document.addEventListener("click", function (e) {
    menus.forEach(function (d) { if (d.open && !d.contains(e.target)) d.open = false; });
  });

  document.addEventListener("keydown", function (e) {
    if (e.key !== "Escape") return;
    menus.forEach(function (d) {
      if (d.open) { d.open = false; d.querySelector("summary").focus(); }
    });
  });

  // Phone menu is display:none above 900px (styles.css); if the window
  // grows while it's open, close it so the scroll lock can't stick.
  window.addEventListener("resize", function () {
    var m = document.querySelector(".nav-menu");
    if (m && m.open && window.innerWidth > 900) m.open = false;
  });

  // The Industries menu's photos are lazy (closed <details>), so the first
  // open showed grey boxes for a moment: start fetching them as soon as the
  // pointer or keyboard reaches "Industries".
  var drop = document.querySelector(".nav-drop");
  if (drop) {
    var warm = function () {
      drop.querySelectorAll("img").forEach(function (img) { new Image().src = img.src; });
      drop.removeEventListener("pointerenter", warm);
      drop.removeEventListener("focusin", warm);
    };
    drop.addEventListener("pointerenter", warm);
    drop.addEventListener("focusin", warm);
  }
})();

// Homepage industry switcher (scripts/marketing-pages.mjs renders it).
// Without this script every panel shows stacked and the tab row stays
// hidden; with it, one industry at a time. Arrow keys, Home and End move
// between tabs (WAI-ARIA tabs pattern). No auto-rotate: the desktop page
// stays still unless the visitor acts (owner direction 2026-09-11). All
// six tabs are always in view (two rows on phones), so the row never
// scrolls sideways (owner 2026-10-06).
(function () {
  var root = document.querySelector("[data-showcase]");
  if (!root) return;
  var list = root.querySelector(".sc-tabs");
  var tabs = Array.prototype.slice.call(root.querySelectorAll(".sc-tab"));
  if (!list || !tabs.length) return;

  function select(tab, focus) {
    tabs.forEach(function (t) {
      var on = t === tab;
      t.setAttribute("aria-selected", on ? "true" : "false");
      t.tabIndex = on ? 0 : -1;
      document.getElementById(t.getAttribute("aria-controls")).hidden = !on;
    });
    if (focus) tab.focus();
  }

  tabs.forEach(function (t, i) {
    t.addEventListener("click", function () { select(t, false); });
    t.addEventListener("keydown", function (e) {
      var n = { ArrowRight: i + 1, ArrowLeft: i - 1, Home: 0, End: tabs.length - 1 }[e.key];
      if (n === undefined) return;
      e.preventDefault();
      select(tabs[(n + tabs.length) % tabs.length], true);
    });
  });

  list.hidden = false;
  root.classList.add("is-tabs");
  select(tabs[0], false);
})();

// Homepage hero A3, "The Signature, clean phone" (owner pick 2026-10-09).
// Hover or focus a crew card and "work" in the h1 becomes that crew while
// the phone in the middle shows that industry's real Home screen (and its
// clock); leave and it settles back to the café. On
// a desktop nothing moves by itself. Touch screens (hover: none — phones,
// tablets and iPad landscape) step through the crews every 2.5s while the
// hero is on screen, pausing whenever the visitor touches the row or tabs
// onto a card, with a Pause / Play button (WCAG 2.2.2); never under
// reduced motion. In the swipeable row (under 1000px) the crew snapped to
// the centre drives the headline. The h1 keeps its real text: crew words
// are aria-hidden overlays and "work" only fades, so screen readers always
// hear one stable line. Per-crew data (word, screen, alt text, clock) is
// on each card's data-* attributes, generated by
// scripts/marketing-pages.mjs. Without this script the hero is the plain
// tagline, six links and the café's Home screen.
(function () {
  var hero = document.querySelector(".hero.sig");
  if (!hero) return;
  var slot = hero.querySelector("[data-slot]");
  var row = hero.querySelector(".crews");
  var shotBox = hero.querySelector("[data-shots]");
  var cards = Array.prototype.slice.call(hero.querySelectorAll(".crew[data-key]"));
  if (!slot || !row || !shotBox || !cards.length) return;
  var clock = hero.querySelector("[data-dev-time]");

  var mq = function (q) { try { return window.matchMedia(q); } catch (e) { return { matches: false }; } };
  var reduce = mq("(prefers-reduced-motion: reduce)");
  var rowMode = mq("(max-width: 999px)");
  var touchCycle = mq("(hover: none)");
  var byKey = {};
  cards.forEach(function (c) { byKey[c.getAttribute("data-key")] = c; });

  // ---- the phone's screen ----
  // The café's Home is in the HTML (the opening view); each other crew's
  // screen is added the first time it's wanted and cross-fades in once
  // loaded, with the status-bar clock from that screenshot (data-time).
  var baseShot = shotBox.querySelector("img");
  var baseKey = baseShot.getAttribute("data-key");
  var openTime = clock ? clock.textContent : "";
  var shots = {}, want = baseKey;
  shots[baseKey] = baseShot;
  function shot(key) {
    var card = byKey[key];
    if (!card) return null;
    if (shots[key]) return shots[key];
    var img = document.createElement("img");
    img.className = "is-extra";
    img.alt = card.getAttribute("data-screen-alt") || "";
    img.width = 600; img.height = 1301; img.decoding = "async";
    img.setAttribute("aria-hidden", "true");
    img.src = card.getAttribute("data-screen");
    shotBox.appendChild(img);
    shots[key] = img;
    return img;
  }
  function setScreen(key) {
    var k = key || baseKey;
    want = k;
    var img = shot(k);
    if (!img) return;
    function show() {
      if (want !== k) return;
      Object.keys(shots).forEach(function (s) {
        var on = s === k;
        if (shots[s] === baseShot) baseShot.classList.toggle("is-off", !on);
        else shots[s].classList.toggle("is-on", on);
        if (on) shots[s].removeAttribute("aria-hidden"); else shots[s].setAttribute("aria-hidden", "true");
      });
      if (clock) clock.textContent = key ? byKey[key].getAttribute("data-time") || openTime : openTime;
    }
    if (img.complete && img.naturalWidth) show(); else img.addEventListener("load", show, { once: true });
  }
  function preloadAll() { cards.forEach(function (c) { shot(c.getAttribute("data-key")); }); }

  // ---- the word slot ----
  // The real word stays in the h1 (screen readers and crawlers always get
  // "Your work crew, sorted."). It only fades to transparent while an
  // aria-hidden crew word is laid over it.
  var homeWord = slot.textContent.trim();
  slot.textContent = "";
  var home = document.createElement("span");
  home.className = "slot-w slot-home";
  home.textContent = homeWord;
  slot.appendChild(home);
  slot.classList.add("is-live");
  var cur = home, curWord = homeWord;
  function fit(noAnim) {
    if (noAnim) slot.style.transition = "none";
    slot.style.width = cur.offsetWidth + "px";
    if (noAnim) { slot.getBoundingClientRect(); slot.style.transition = ""; }
  }
  fit(true);

  function setWord(w) {
    if (w === curWord) return;
    curWord = w;
    var old = cur, next;
    if (w === homeWord) {
      next = home;
      next.classList.add("is-enter");
      next.classList.remove("is-leave");
    } else {
      next = document.createElement("span");
      next.className = "slot-w is-enter";
      next.setAttribute("aria-hidden", "true");
      next.textContent = w;
      slot.appendChild(next);
    }
    cur = next;
    old.classList.add("is-leave");
    next.getBoundingClientRect();
    next.classList.remove("is-enter");
    slot.style.width = next.offsetWidth + "px";
    if (old !== home) setTimeout(function () { if (old.parentNode) old.parentNode.removeChild(old); }, 320);
  }

  // ---- one active crew at a time ----
  var active = null;
  function activate(card) {
    if (active === card) return;
    if (active) active.classList.remove("is-active");
    active = card;
    if (card) {
      card.classList.add("is-active");
      setWord(card.getAttribute("data-word"));
      setScreen(card.getAttribute("data-key"));
    } else {
      setWord(homeWord);
      setScreen(null);
    }
  }

  // ---- desktop: hover / focus ----
  var leaveTimer;
  function settle() {
    var f = document.activeElement;
    if (f && cards.indexOf(f) > -1) { activate(f); return; }
    if (rowMode.matches) return; // the row keeps its centred crew
    activate(null);
  }
  cards.forEach(function (c) {
    c.addEventListener("pointerenter", function (e) {
      if (e.pointerType === "touch" || rowMode.matches) return;
      clearTimeout(leaveTimer);
      activate(c);
    });
    c.addEventListener("pointerleave", function (e) {
      if (e.pointerType === "touch" || rowMode.matches) return;
      clearTimeout(leaveTimer);
      leaveTimer = setTimeout(settle, 160);
    });
    c.addEventListener("focus", function () {
      clearTimeout(leaveTimer);
      activate(c);
      if (rowMode.matches) centre(c, true);
    });
    c.addEventListener("blur", function () {
      clearTimeout(leaveTimer);
      leaveTimer = setTimeout(settle, 160);
    });
  });
  // the phone holds the crew you came from, so you can move onto it to
  // read the screen; leaving it settles back like leaving a card
  var phoneCard = hero.querySelector(".sig-phone");
  if (phoneCard) {
    phoneCard.addEventListener("pointerenter", function (e) {
      if (e.pointerType !== "touch" && !rowMode.matches) clearTimeout(leaveTimer);
    });
    phoneCard.addEventListener("pointerleave", function (e) {
      if (e.pointerType === "touch" || rowMode.matches) return;
      clearTimeout(leaveTimer);
      leaveTimer = setTimeout(settle, 160);
    });
  }
  // fetch the six screens once the page is idle (arc layout only;
  // ~300 KB), so the first hover crossfades without a wait
  function idlePreload() {
    if (rowMode.matches) return;
    var idle = window.requestIdleCallback || function (f) { return setTimeout(f, 1200); };
    idle(preloadAll);
  }
  if (document.readyState === "complete") idlePreload();
  else window.addEventListener("load", idlePreload);
  row.addEventListener("pointerenter", function () { if (!rowMode.matches) preloadAll(); }, { once: true });

  // ---- row mode: the centred crew drives the headline ----
  var programmatic = false, progTimer, spyTicking = false;
  function centre(card, smooth) {
    if (!rowMode.matches) return; // the arc never scrolls
    var r = row.getBoundingClientRect(), cr = card.getBoundingClientRect();
    var delta = (cr.left + cr.width / 2) - (r.left + r.width / 2);
    if (Math.abs(delta) < 2) return;
    programmatic = true;
    clearTimeout(progTimer);
    progTimer = setTimeout(function () { programmatic = false; }, 900);
    try {
      row.scrollTo({ left: row.scrollLeft + delta, behavior: smooth && !reduce.matches ? "smooth" : "auto" });
    } catch (e) { row.scrollLeft += delta; }
  }
  function centredCard() {
    var r = row.getBoundingClientRect(), mid = r.left + r.width / 2, best = null, bestD = Infinity;
    cards.forEach(function (c) {
      var cr = c.getBoundingClientRect(), d = Math.abs(cr.left + cr.width / 2 - mid);
      if (d < bestD) { bestD = d; best = c; }
    });
    return best;
  }
  row.addEventListener("scroll", function () {
    if (!rowMode.matches || programmatic || spyTicking) return;
    spyTicking = true;
    requestAnimationFrame(function () {
      spyTicking = false;
      var c = centredCard();
      if (c && c !== active) { activate(c); step = cards.indexOf(c); }
    });
  }, { passive: true });

  // ---- touch screens only: the gentle cycle, with a pause button ----
  var step = -1, pausedUntil = 0, stopped = false;
  var pauseBtn = hero.querySelector("[data-pause]");
  var pauseLabel = pauseBtn && pauseBtn.querySelector("[data-pause-label]");
  function cycling() { return touchCycle.matches && !reduce.matches; }
  function syncPause() {
    if (!pauseBtn || !pauseLabel) return;
    pauseBtn.hidden = !cycling();
    pauseBtn.classList.toggle("is-paused", stopped);
    pauseLabel.textContent = stopped ? "Play" : "Pause";
    pauseBtn.setAttribute("aria-label", stopped ? "Play: step through the crews" : "Pause: stop stepping through the crews");
  }
  if (pauseBtn) {
    pauseBtn.addEventListener("click", function () {
      stopped = !stopped;
      if (!stopped) pausedUntil = 0;
      syncPause();
    });
  }
  syncPause();
  [reduce, touchCycle].forEach(function (m) {
    try { m.addEventListener("change", syncPause); }
    catch (e) { try { m.addListener(syncPause); } catch (e2) { /* static is fine */ } }
  });
  function pause(ms) { pausedUntil = Date.now() + ms; }
  ["touchstart", "pointerdown", "wheel"].forEach(function (ev) {
    row.addEventListener(ev, function () {
      pause(6000);
      programmatic = false;            // the visitor's own swipe always wins
      clearTimeout(progTimer);
    }, { passive: true });
  });
  row.addEventListener("touchend", function () { pause(4000); }, { passive: true });
  function tick() {
    if (stopped || !cycling() || document.hidden) return;
    if (Date.now() < pausedUntil) return;
    if (cards.indexOf(document.activeElement) > -1) return; // keyboard on a card
    var hr = hero.getBoundingClientRect();
    if (hr.bottom < 120 || hr.top > window.innerHeight) return;
    step = (step + 1) % (cards.length + 1);       // six crews, then "work"
    var c = cards[step] || null;
    activate(c);
    centre(c || cards[1], true);              // row only; "work": back to the opening view
    var next = cards[step + 1];
    if (next) shot(next.getAttribute("data-key")); // fetch one ahead
  }
  setInterval(tick, 2500);

  // row mode opens on the second crew, so there's a neighbour on each
  // side (and it's plain the row scrolls both ways); nothing is
  // "active" until the visitor swipes or the cycle starts
  function openRow() { if (rowMode.matches && cards[1]) centre(cards[1], false); }
  openRow();

  // ---- keep the slot measured; switching layouts clears the state ----
  var wasRow = rowMode.matches, resizeTicking = false;
  window.addEventListener("resize", function () {
    if (resizeTicking) return;
    resizeTicking = true;
    requestAnimationFrame(function () {
      resizeTicking = false;
      fit(true);
      syncPause();
      if (wasRow !== rowMode.matches) { wasRow = rowMode.matches; activate(null); step = -1; openRow(); }
    });
  });
})();
