// teammateapp.au — shared page behaviour (every page loads this, deferred;
// each block below checks for its own elements first).
// The header menus are plain <details>, so they already open and close
// without JS; this only adds the polish: one menu open at a time, close on
// a click outside, on Escape or on following a link, and no page scroll
// behind the full-screen phone menu.
(function () {
  var menus = Array.prototype.slice.call(document.querySelectorAll(".nav details"));
  if (!menus.length) return;

  function sync() {
    var phoneMenu = document.querySelector(".nav-menu");
    document.documentElement.classList.toggle("menu-open", !!(phoneMenu && phoneMenu.open));
  }

  menus.forEach(function (d) {
    d.addEventListener("toggle", function () {
      if (d.open) menus.forEach(function (o) { if (o !== d) o.open = false; });
      sync();
    });
    d.addEventListener("click", function (e) {
      if (e.target.closest("a")) d.open = false;
    });
  });

  document.addEventListener("click", function (e) {
    menus.forEach(function (d) { if (d.open && !d.contains(e.target)) d.open = false; });
  });

  document.addEventListener("keydown", function (e) {
    if (e.key !== "Escape") return;
    menus.forEach(function (d) {
      if (d.open) { d.open = false; d.querySelector("summary").focus(); }
    });
  });

  // Phone menu is display:none above 900px (styles.css); if the window
  // grows while it's open, close it so the scroll lock can't stick.
  window.addEventListener("resize", function () {
    var m = document.querySelector(".nav-menu");
    if (m && m.open && window.innerWidth > 900) m.open = false;
  });

  // The Industries menu's photos are lazy (closed <details>), so the first
  // open showed grey boxes for a moment: start fetching them as soon as the
  // pointer or keyboard reaches "Industries".
  var drop = document.querySelector(".nav-drop");
  if (drop) {
    var warm = function () {
      drop.querySelectorAll("img").forEach(function (img) { new Image().src = img.src; });
      drop.removeEventListener("pointerenter", warm);
      drop.removeEventListener("focusin", warm);
    };
    drop.addEventListener("pointerenter", warm);
    drop.addEventListener("focusin", warm);
  }
})();

// Homepage industry switcher (scripts/marketing-pages.mjs renders it).
// Without this script every panel shows stacked and the tab row stays
// hidden; with it, one industry at a time. Arrow keys, Home and End move
// between tabs (WAI-ARIA tabs pattern). No auto-rotate: the desktop page
// stays still unless the visitor acts (owner direction 2026-09-11). All
// six tabs are always in view (two rows on phones), so the row never
// scrolls sideways (owner 2026-10-06).
(function () {
  var root = document.querySelector("[data-showcase]");
  if (!root) return;
  var list = root.querySelector(".sc-tabs");
  var tabs = Array.prototype.slice.call(root.querySelectorAll(".sc-tab"));
  if (!list || !tabs.length) return;

  function select(tab, focus) {
    tabs.forEach(function (t) {
      var on = t === tab;
      t.setAttribute("aria-selected", on ? "true" : "false");
      t.tabIndex = on ? 0 : -1;
      document.getElementById(t.getAttribute("aria-controls")).hidden = !on;
    });
    if (focus) tab.focus();
  }

  tabs.forEach(function (t, i) {
    t.addEventListener("click", function () { select(t, false); });
    t.addEventListener("keydown", function (e) {
      var n = { ArrowRight: i + 1, ArrowLeft: i - 1, Home: 0, End: tabs.length - 1 }[e.key];
      if (n === undefined) return;
      e.preventDefault();
      select(tabs[(n + tabs.length) % tabs.length], true);
    });
  });

  list.hidden = false;
  root.classList.add("is-tabs");
  select(tabs[0], false);
})();

// Homepage hero B, "Words left, crew photo + phone right" (owner pick
// 2026-10-09). Hover or focus a crew face and "work" in the h1 becomes
// that crew while the photo, the phone's real Home screen and the
// clock-in moment change to match; leave and it settles back to the café.
// On a desktop nothing moves by itself. Touch screens (hover: none —
// phones, tablets and iPad landscape) step through the crews every 2.5s
// while the hero is on screen, pausing whenever the visitor touches the
// faces, with a Pause / Play button (WCAG 2.2.2); never under reduced
// motion. The h1 keeps its real text: crew words are aria-hidden overlays
// and "work" only fades, so screen readers always hear one stable line.
// Per-crew data (word, photo, screen, alt text, clock, moment) is on each
// face's data-* attributes, generated by scripts/marketing-pages.mjs.
// Without this script the hero is the plain tagline, six links, the café
// photo and its Home screen.
(function () {
  var hero = document.querySelector(".hero.lead");
  if (!hero) return;
  var slot = hero.querySelector("[data-slot]");
  var row = hero.querySelector(".faces");
  var photoBox = hero.querySelector("[data-photo-box]");
  var shotBox = hero.querySelector("[data-shots]");
  var faces = Array.prototype.slice.call(hero.querySelectorAll(".face[data-key]"));
  if (!slot || !row || !photoBox || !shotBox || !faces.length) return;
  var clock = hero.querySelector("[data-dev-time]");
  var chip = {
    who: hero.querySelector("[data-chip-who]"),
    when: hero.querySelector("[data-chip-when]"),
    where: hero.querySelector("[data-chip-where]"),
  };

  var mq = function (q) { try { return window.matchMedia(q); } catch (e) { return { matches: false }; } };
  var reduce = mq("(prefers-reduced-motion: reduce)");
  var touchCycle = mq("(hover: none)");

  // ---- photo and phone screen layers, made on demand ----
  // The café photo and its Home screen are in the HTML (the opening view);
  // the other crews' layers are added the first time they're wanted and
  // cross-fade in once loaded.
  var basePhoto = photoBox.querySelector("img");
  var baseShot = shotBox.querySelector("img");
  var baseKey = basePhoto.getAttribute("data-key");
  var photos = {}, shots = {};
  photos[baseKey] = basePhoto;
  shots[baseKey] = baseShot;
  var byKey = {};
  faces.forEach(function (f) { byKey[f.getAttribute("data-key")] = f; });
  var openData = {
    time: clock ? clock.textContent : "",
    who: chip.who ? chip.who.textContent : "",
    when: chip.when ? chip.when.textContent : "",
    where: chip.where ? chip.where.textContent : "",
  };

  function layers(key) {
    var f = byKey[key];
    if (!f || photos[key]) return;
    var p = document.createElement("img");
    p.alt = "";
    p.width = 1600; p.height = 900; p.decoding = "async";
    p.sizes = basePhoto.getAttribute("sizes");
    p.style.objectPosition = f.getAttribute("data-focus") || "50% 50%";
    p.srcset = f.getAttribute("data-photo");
    photoBox.appendChild(p);
    photos[key] = p;
    var s = document.createElement("img");
    s.className = "is-extra";
    s.alt = f.getAttribute("data-screen-alt") || "";
    s.width = 600; s.height = 1301; s.decoding = "async";
    s.setAttribute("aria-hidden", "true");
    s.src = f.getAttribute("data-screen");
    shotBox.appendChild(s);
    shots[key] = s;
  }
  function ready(img, fn) {
    if (img.complete && img.naturalWidth) fn(); else img.addEventListener("load", fn, { once: true });
  }
  var want = baseKey;
  function setPicture(key) {
    want = key;
    layers(key);
    var p = photos[key], s = shots[key];
    if (!p || !s) return;
    var waiting = 2;
    function show() {
      if (--waiting || want !== key) return;
      Object.keys(photos).forEach(function (k) { photos[k].classList.toggle("is-on", k === key); });
      Object.keys(shots).forEach(function (k) {
        var on = k === key;
        if (shots[k] === baseShot) baseShot.classList.toggle("is-off", !on);
        else shots[k].classList.toggle("is-on", on);
        if (on) shots[k].removeAttribute("aria-hidden"); else shots[k].setAttribute("aria-hidden", "true");
      });
      var f = byKey[key];
      var d = key === baseKey && !active ? openData : {
        time: f.getAttribute("data-time"), who: f.getAttribute("data-who"),
        when: f.getAttribute("data-when"), where: f.getAttribute("data-where"),
      };
      if (clock) clock.textContent = d.time;
      if (chip.who) chip.who.textContent = d.who;
      if (chip.when) chip.when.textContent = d.when;
      if (chip.where) chip.where.textContent = d.where;
    }
    ready(p, show);
    ready(s, show);
  }
  function preloadAll() { faces.forEach(function (f) { layers(f.getAttribute("data-key")); }); }

  // ---- the word slot ----
  // The real word stays in the h1 (screen readers and crawlers always get
  // "Your work crew, sorted."). It only fades to transparent while an
  // aria-hidden crew word is laid over it.
  var homeWord = slot.textContent.trim();
  slot.textContent = "";
  var home = document.createElement("span");
  home.className = "slot-w slot-home";
  home.textContent = homeWord;
  slot.appendChild(home);
  slot.classList.add("is-live");
  var cur = home, curWord = homeWord;
  function fit(noAnim) {
    if (noAnim) slot.style.transition = "none";
    slot.style.width = cur.offsetWidth + "px";
    if (noAnim) { slot.getBoundingClientRect(); slot.style.transition = ""; }
  }
  fit(true);
  if (document.fonts && document.fonts.ready) document.fonts.ready.then(function () { fit(true); });

  function setWord(w) {
    if (w === curWord) return;
    curWord = w;
    var old = cur, next;
    if (w === homeWord) {
      next = home;
      next.classList.add("is-enter");
      next.classList.remove("is-leave");
    } else {
      next = document.createElement("span");
      next.className = "slot-w is-enter";
      next.setAttribute("aria-hidden", "true");
      next.textContent = w;
      slot.appendChild(next);
    }
    cur = next;
    old.classList.add("is-leave");
    next.getBoundingClientRect();
    next.classList.remove("is-enter");
    slot.style.width = next.offsetWidth + "px";
    if (old !== home) setTimeout(function () { if (old.parentNode) old.parentNode.removeChild(old); }, 320);
  }

  // ---- one active crew at a time ----
  var active = null;
  function activate(face) {
    if (active === face) return;
    if (active) active.classList.remove("is-active");
    active = face;
    if (face) {
      face.classList.add("is-active");
      setWord(face.getAttribute("data-word"));
      setPicture(face.getAttribute("data-key"));
    } else {
      setWord(homeWord);
      setPicture(baseKey);
    }
  }

  // ---- desktop: hover / focus ----
  var leaveTimer;
  function settle() {
    var f = document.activeElement;
    activate(f && faces.indexOf(f) > -1 ? f : null);
  }
  faces.forEach(function (f) {
    f.addEventListener("pointerenter", function (e) {
      if (e.pointerType === "touch") return;
      clearTimeout(leaveTimer);
      activate(f);
    });
    f.addEventListener("pointerleave", function (e) {
      if (e.pointerType === "touch") return;
      clearTimeout(leaveTimer);
      leaveTimer = setTimeout(settle, 160);
    });
    f.addEventListener("focus", function () { clearTimeout(leaveTimer); activate(f); });
    f.addEventListener("blur", function () { clearTimeout(leaveTimer); leaveTimer = setTimeout(settle, 160); });
  });
  // fetch the other crews' photos and screens once the page is idle
  // (~550 KB), so the first hover cross-fades without a wait
  function idlePreload() {
    var idle = window.requestIdleCallback || function (fn) { return setTimeout(fn, 1200); };
    idle(preloadAll);
  }
  if (document.readyState === "complete") idlePreload();
  else window.addEventListener("load", idlePreload);
  row.addEventListener("pointerenter", preloadAll, { once: true });

  // ---- touch screens only: the gentle cycle, with a pause button ----
  var step = -1, pausedUntil = 0, stopped = false;
  var pauseBtn = hero.querySelector("[data-pause]");
  var pauseLabel = pauseBtn && pauseBtn.querySelector("[data-pause-label]");
  function cycling() { return touchCycle.matches && !reduce.matches; }
  function syncPause() {
    if (!pauseBtn || !pauseLabel) return;
    pauseBtn.hidden = !cycling();
    pauseBtn.classList.toggle("is-paused", stopped);
    pauseLabel.textContent = stopped ? "Play" : "Pause";
    pauseBtn.setAttribute("aria-label", stopped ? "Play: step through the crews" : "Pause: stop stepping through the crews");
  }
  if (pauseBtn) {
    pauseBtn.addEventListener("click", function () {
      stopped = !stopped;
      if (!stopped) pausedUntil = 0;
      syncPause();
    });
  }
  syncPause();
  [reduce, touchCycle].forEach(function (m) {
    try { m.addEventListener("change", syncPause); }
    catch (e) { try { m.addListener(syncPause); } catch (e2) { /* static is fine */ } }
  });
  ["touchstart", "pointerdown"].forEach(function (ev) {
    row.addEventListener(ev, function () { pausedUntil = Date.now() + 6000; }, { passive: true });
  });
  function tick() {
    if (stopped || !cycling() || document.hidden) return;
    if (Date.now() < pausedUntil) return;
    if (faces.indexOf(document.activeElement) > -1) return; // keyboard on a face
    var hr = hero.getBoundingClientRect();
    if (hr.bottom < 120 || hr.top > window.innerHeight) return;
    step = (step + 1) % (faces.length + 1);      // six crews, then "work"
    activate(faces[step] || null);
    var next = faces[step + 1];
    if (next) layers(next.getAttribute("data-key")); // fetch one ahead
  }
  setInterval(tick, 2500);

  // ---- keep the slot measured ----
  var resizeTicking = false;
  window.addEventListener("resize", function () {
    if (resizeTicking) return;
    resizeTicking = true;
    requestAnimationFrame(function () { resizeTicking = false; fit(true); syncPause(); });
  });
})();
